### ISSUE TITLE
GetInfoPlistPathAction get the wrong plist path

### ISSUE THREAD

**Issue by btxkenshin** [SiarheiFedartsou/fastlane-plugin-versioning#1]
![89ce9a1d-ef9a-4f90-8bd3-4488e53e3ce4](https://cloud.githubusercontent.com/assets/1837666/18949030/0f43aa3c-866c-11e6-8c1c-561ae5771e04.png)

Here is the setting:
```
increment_build_number_in_plist(
      build_number: "23",
      xcodeproj: './Heihei/Heihei.xcodeproj'
      target: "Heihei"
    )
```

Get the wrong Info.plist , should be 

`/Source/heihei_ios/Heihei/Heihei/Info.plist`

not 

`/Source/heihei_ios/Heihei/Info.plist`

![image](https://cloud.githubusercontent.com/assets/1837666/18949102/67742ae2-866c-11e6-9b8a-338751d6f104.png)

**Comment by SiarheiFedartsou** [comment]
@btxkenshin Could you please make a simple bug demonstration app and fastlane configuration and share it with me please?

**Comment by SiarheiFedartsou** [comment]
If problem is still happened than re-open issue please.
