### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by gelldur** [SiarheiFedartsou/fastlane-plugin-versioning#11]
```
mac-04:tools gelldur$ sudo fastlane add_plugin versioning
[14:48:35]: Plugin 'fastlane-plugin-versioning' was added to './fastlane/Pluginfile'
[14:48:35]: It looks like fastlane plugins are not yet set up for this project.
[14:48:35]: fastlane will create a new Gemfile at path 'Gemfile'
[14:48:35]: This change is necessary for fastlane plugins to work
[14:48:35]: Should fastlane modify the Gemfile at path 'Gemfile' for you? (y/n)
y
[14:48:47]: Successfully modified 'Gemfile'
[14:48:47]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/gelldur/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
/Users/gelldur/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170613-66909-f3jt6o.rb extconf.rb
creating Makefile

current directory: /Users/gelldur/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/gelldur/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
[-Wmissing-sysroot]
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/gelldur/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/gelldur/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/gelldur/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/gelldur/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0 for inspection.
Results logged to /Users/gelldur/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.1.0/gem_make.out

An error occurred while installing json (2.1.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.1.0'` succeeds before bundling.
```

```
mac-04:tools gelldur$ sudo gem install json -v '2.1.0'
Building native extensions.  This could take a while...
Successfully installed json-2.1.0
Parsing documentation for json-2.1.0
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/json/ext/generator.bundle, skipping
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/json/ext/parser.bundle, skipping
1 gem installed
```

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
# json_key_file "/path/to/your/downloaded/key.json" # GooglePlay
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.38.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| slack-notifier             | 1.5.1        |
| CFPropertyList             | 2.3.5        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.4.4        |
| rouge                      | 1.11.1       |
| xcpretty                   | 0.2.6        |
| unicode-display_width      | 1.1.3        |
| terminal-table             | 1.7.3        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.1        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.5.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.8        |
| commander-fastlane         | 4.4.4        |
| faraday                    | 0.12.1       |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| fastimage                  | 2.1.0        |
| gh_inspector               | 1.0.3        |
| uber                       | 0.0.15       |
| representable              | 2.3.0        |
| retriable                  | 2.1.0        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| hurley                     | 0.2          |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.1       |
| logging                    | 2.2.2        |
| jwt                        | 1.5.6        |
| memoist                    | 0.15.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.1        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.9.28       |
| json                       | 1.8.1        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 0.0.4        |
| bundler                    | 1.14.6       |
| faraday_middleware         | 0.11.0.1     |
| excon                      | 0.56.0       |
| plist                      | 3.3.0        |
| claide                     | 1.0.2        |
| fastlane-plugin-versioning | 0.2.7        |
</details>

*generated on:* **2017-06-13**
</details>
```

**Comment by gelldur** [comment]
On the end `get_version_number_from_plist` and `get_build_number_from_plist` are working....

**Comment by SiarheiFedartsou** [comment]
@gelldur I think this error is not caused by my plugin. Maybe you should update ruby version or Xcode(I see you have pretty old version 7.3.1)? 
Feel free to re-open this issue if you think that problem was caused by this plugin.

**Comment by gelldur** [comment]
@SiarheiFedartsou I don't know from where it gets XCode version because i have only current version 8.3 ? Something like that

**Comment by SiarheiFedartsou** [comment]
@gelldur just found a thread with similar problem https://github.com/fastlane/fastlane/issues/7691

**Comment by gelldur** [comment]
@SiarheiFedartsou ok thx :)

**Comment by choli** [comment]
@gelldur Any news on this? Running into the same problem. Same 7.3.1 version and osx 10.11 is somewhere, but cannot where to remove it...

**Comment by gelldur** [comment]
@choli nope. In my case it simply installs (with fails but it is working)

**Comment by HardikDG** [comment]
Same here it is showing the error in installation, still, actions are working. 

I have tried with Sudo/Sudoless if it's permission issue but it fails in installation in both the case

**Comment by ppamorim** [comment]
Same here
