### ISSUE TITLE
Support for bitbucket pipeline build number

### ISSUE THREAD

**Issue by krantik** [SiarheiFedartsou/fastlane-plugin-versioning#14]
As part of the ci_build_number, is there a plan to get bitbucket pipeline build number. It is available as env variable $BITBUCKET_BUILD_NUMBER

**Comment by SiarheiFedartsou** [comment]
@krantik 
Hi, just released version 0.3.1 with Bitbucket Pipelines support in `ci_build_number` action. 
Also I will be very grateful if you give this project a star. :)

**Comment by krantik** [comment]
@SiarheiFedartsou Thank you, it looks good.
