### ISSUE TITLE
Incrementing Minor Version Format

### ISSUE THREAD

**Issue by pokono** [SiarheiFedartsou/fastlane-plugin-versioning#15]
Incrementing minor version number should create a version number of the following format: `x.x` instead of `x.x.0`.
This is probably a question of style, but would be great to be able to specify this behaviour.

**Comment by SiarheiFedartsou** [comment]
Hello! Thanks for the feedback. I've added `omit_zero_patch_version` flag to `increment_version_number_in_plist` action and released version 0.3.3. 
So, I think issue can be closed. Feel free to re-open it or create new one in case of other issues.
