### ISSUE TITLE
An error occurred while installing unf_ext (0.0.7.4)

### ISSUE THREAD

**Issue by connected-space** [SiarheiFedartsou/fastlane-plugin-versioning#17]
Keep getting this error 

An error occurred while installing unf_ext (0.0.7.4), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.4'` succeeds before bundling.

**Comment by SiarheiFedartsou** [comment]
It seems to be some common Ruby issue. I can suggest you to try some solutions from Google(for ex. this one https://stackoverflow.com/questions/35473812/installing-unf-ext-0-0-7-2-not-working ). And also feel free to re-open this issue if you believe that problem was caused by this plugin.
