### ISSUE TITLE
undefined method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by CYBoys** [SiarheiFedartsou/fastlane-plugin-versioning#19]
sorry, I don't know that what happened。
I can some target, but some not.Are all calling the same method。

Here is an error。

[20:41:43]: --- Step: increment_build_number_in_plist ---
[20:41:43]: ---------------------------------------------
[20:41:43]: undefined method `[]' for nil:NilClass 

[20:41:43]: Unable to find plist file at '/Users/laiyoung_/Documents/QT/QingTui_iPhone/${SRCROOT}/QingTui_iPhone/QingTui_Distribution/QingTui_Distribution.plist'
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios Archive |
| BUILD_NUMBER     | true        |
+------------------+-------------+
[20:41:43]: undefined method `split' for true:TrueClass

my method

    private_lane :UpdateBuild_number do |options|
      qt_target_name = options[:qt_target_name]
      increment_build_number_in_plist(target: "QingTui_#{qt_target_name}") 
      increment_build_number_in_plist(target: "Share_#{qt_target_name}") 
      build_number = get_info_plist_value(path: "./QingTui_iPhone/QingTui_#{qt_target_name}/QingTui_#{qt_target_name}.plist", key: "CFBundleVersion")

      # git_commit(path: "./QingTui_iPhone", message: "update build_number to #{build_number}") 
      # push_to_git_remote 

      puts build_number
      build_number
    end

thank you!

**Comment by SiarheiFedartsou** [comment]
@CYBoys Hi, thanks for posting this. Do you have some relative paths in your Info.plist path setting?

**Comment by CYBoys** [comment]
Thank you for answering！
'/Users/laiyoung_/Documents/QT/QingTui_iPhone/${SRCROOT}/QingTui_iPhone/QingTui_Distribution/QingTui_Distribution.plist'，This path is wrong。
The right should be like this '/Users/laiyoung_/Documents/QT/QingTui_iPhone/QingTui_iPhone/QingTui_Distribution/QingTui_Distribution.plist'.

**Comment by SiarheiFedartsou** [comment]
@CYBoys Sorry, I think you misunderstood my question. Could you share this value from your build settings?
![Screenshot](https://4.downloader.disk.yandex.ru/preview/30eeaffd295f2f4a5cc36ff7f5f304485d5d5d58f1c387becc3a4343fb156aad/inf/T4xlPBDrhsto4QKNgR0T6T54-lByazFD_6I4cpW8pkN5yo7GK-dyYmHIuxX4l6oHcoA_SI6l3Ld-gllIfJ2-fA%3D%3D?uid=0&filename=2018-01-19_10-58-05.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by CYBoys** [comment]
![image](https://user-images.githubusercontent.com/15981638/35140526-8e8602e8-fd32-11e7-9a95-93c404fd8c04.png)

**Comment by CYBoys** [comment]
@SiarheiFedartsou But my target is also like that, Such as this is no problem
![image](https://user-images.githubusercontent.com/15981638/35140695-30427904-fd33-11e7-8dfd-6ad2eb5e2156.png)

**Comment by SiarheiFedartsou** [comment]
@CYBoys It seems that you use `@{SRCROOT}`, but not `@(SRCROOT)`(difference in brackets types). This plugin currently substitutes only `@(SRCROOT)`, I didn't know that Xcode supports curly braces for such kind of variables. So, as a workaround I can recommend you to use `@(SRCROOT)` until I fix it(I think I will in a couple of days).

**Comment by SiarheiFedartsou** [comment]
@CYBoys just make a double-click on this value and I believe you will see `@{SRCROOT}` there :)

**Comment by CYBoys** [comment]
So, thank you！

**Comment by SiarheiFedartsou** [comment]
Keep it open until fix of `${SRCROOT}` issue.

**Comment by CYBoys** [comment]
ok

**Comment by SiarheiFedartsou** [comment]
@CYBoys Just fixed this issue and released version 0.3.4. Please check if it is working with curly brackets(with `${SRCROOT}`) after update and feel free to re-open this issue in case of any problems.
