### ISSUE TITLE
increment_version_number_in_plist removes the location permission descriptions from the plist

### ISSUE THREAD

**Issue by vishal-zendrive** [SiarheiFedartsou/fastlane-plugin-versioning#26]
I am using xcode 9

**Comment by SiarheiFedartsou** [comment]
Hi! Thanks for reporting it. Could you provide simple example project demonstrating the issue?

**Comment by jdouglas-nz** [comment]
I'm going to close this ticket due to inactivity. Please open one if you are still having issues!
