### ISSUE TITLE
Path for pods project is not the proper one 

### ISSUE THREAD

**Issue by tirrorex** [SiarheiFedartsou/fastlane-plugin-versioning#36]
The setup is a library (specifically a private pod).
We have at the root directory the _Pods.xcodeproj, the fastlane dir and the Example folder (which contains the workspace and other files).
When trying to increment my library target, fastlane gives me the error : 

>   increment_version_number_in_plist(
      bump_type: type, # Automatically increment minor version number
      xcodeproj: "_Pods.xcodeproj",
      target: 'TEST' # or `scheme`
    )

> No such file or directory @ rb_sysopen - /Users/tnoah/Code/toto/Target Support Files/TEST/TEST-Info.plist

The path should be 
> /Users/tnoah/Code/toto/Example/Pods/Target Support Files/TEST/TEST-Info.plist

I assume it comes from the fact that the plugin does not support by default incrementing the version of a pod.

Is there a quickfix for this?
Thanks

**Comment by tirrorex** [comment]
Went the fastest way being modifying directly the related plist.

**Comment by jdouglas-nz** [comment]
@tirrorex - was wondering if there is any reason for you to bump the pods project version info? every time you run a `pod` command -- be it `install` or `update` -- the project is regenerated, no? I haven't really looked into whether it is a 'destructive' change or not. Especially in context of the `info.plist` file. 

Also, as I've just worked on adding support for it, I should mention that Xcode11 has a new 'opinion' about where to store the actual numbers for build/version. It is now in build settings.

 I wonder, Perhaps there is something you could do something in the podfile too -- 
something like below-
```
post_install do |installer|
 installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
         config.build_settings['MARKETING_VERSION'] = <new-version-here>
     end
 end
end
```

**Comment by jdouglas-nz** [comment]
@tirrorex  - I'm going to close this for now, but please reopen if you haven't solved this issue.
