### ISSUE TITLE
Xcode 11 > $(MARKETING_VERSION) 

### ISSUE THREAD

**Issue by ivanichoo** [SiarheiFedartsou/fastlane-plugin-versioning#37]
Hello!
Xcode has changed its version key for build version. It is now $(MARKETING_VERSION).
Any update soon?
Thanks!

**Comment by Lyine0924** [comment]
see this issue [15322]
(https://github.com/fastlane/fastlane/issues/15322)
I thinks it will fix after version.

**Comment by evgeniybaranov** [comment]
hi, any news?

**Comment by jdouglas-nz** [comment]
Hi @evgeniybaranov  - sorry for the long response. I have recently become a contributor, and am working on this now!

**Comment by jdouglas-nz** [comment]
The way it is going to work -- I am defining a couple new actions for explicitly interacting with the xcodeproject version metadata, or alternatively you can pass in a new flag to the existing plist methods, which will on detecting the $(BUILD_SETTING) type format of value, try and resolve from the xcodeproject.

**Comment by bgold0** [comment]
Thanks so much for working on this @jdouglas-nz

**Comment by jdouglas-nz** [comment]
hey all. sorry for the slow turn-around on this one. Life has gotten real busy real fast.

I have an open PR [here](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/pull/39) -- if any of you are Ruby devs by trade or know a lot of Ruby please feel free to have a look. 


Also, Please let me know if the way it would work still works for your use-cases. 

For example -- if you don't provide enough info to resolve a build/version number out of the xcodeproj, are you all fine with it just picking the first? 

Do you often have build configs that have different build numbers? 

At my current employer, we bump everything at the same time.  I'm not sure if that is industry standard, but reach out if you have other default behaviour requests.

**Comment by jdouglas-nz** [comment]
@ivanichoo / @evgeniybaranov - if you haven't already - please update to v0.4.0 and check the new instructions on how to either make the existing plist getter/setters 'magically' move to a xcodeproj build setting (hint `plist_build_setting_support` flag) or switch to the new xcodeproj getters/setters. If the new functionality does what you need, please close this issue 👌

**Comment by joliejuly** [comment]
@jdouglas-nz hey there, I checked v0.4.0, and it works perfectly in my project. Thank you so much! Could you, please, provide a link to the new instructions about `plist_build_setting_support` flag?

**Comment by jdouglas-nz** [comment]
@joliejuly no worries! If you hadn’t found it I would’ve sent you that way anyhow 😬

Please let me know if those ‘instructions’ are enough or if you’d like me to elaborate 👌

**Comment by ivanichoo** [comment]
works great ! thanks ! 👍

**Comment by batashovp** [comment]
Hello!

I use latest version but there are no support for plist_build_setting_support in increment_build_number_in_xcodeproj method.

    increment_build_number_in_xcodeproj(
      plist_build_setting_support: true,
      target: ENV['TARGET']
    )

>Could not find option 'plist_build_setting_support' in the list of available options: build_number, xcodeproj, target, scheme, build_configuration_name 

[REDACTED] fastlane-plugin-versioning [REDACTED] 0.4.0   [REDACTED] get_version_number_from_git_branch    [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] increment_build_number_in_xcodeproj   [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_version_number_from_plist         [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_build_number_from_plist           [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] ci_build_number                       [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_version_number_from_xcodeproj     [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] increment_version_number_in_xcodeproj [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] increment_version_number_in_plist     [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_app_store_version_number          [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_info_plist_path                   [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] get_build_number_from_xcodeproj       [REDACTED]
[REDACTED]                            [REDACTED]         [REDACTED] increment_build_number_in_plist       [REDACTED]

Guys, please help.
Thanks

**Comment by joliejuly** [comment]
@jdouglas-nz The docs look very comprehensive to me 👍. Thank you!

**Comment by luowei** [comment]
我是使用 Xcodeproj 库顺利的解决了xcode11下fastlane 通过get_version_number获取不到版本号的问题。如下：
在Gemfile里添加：`gem "xcodeproj"`
```
project_version = get_version_number(xcodeproj: "xxxx.xcodeproj", target: "xxxx")
project = Xcodeproj::Project.open('../xxxx.xcodeproj')
target = project.targets.first
if project_version !~ /\d+\./
  target.build_configurations.each do |configuration|
    project_version = configuration.build_settings["MARKETING_VERSION"]
  end
end
```
