### ISSUE TITLE
Error when using increment_version_number_in_xcodeproj

### ISSUE THREAD

**Issue by caioremedio** [SiarheiFedartsou/fastlane-plugin-versioning#41]
Im getting the following error when trying to run `increment_version_number_in_xcodeproj`

```
[17:36:14]: Unknown method 'set_version_number_using_target'
[17:36:14]: To call another action from an action use `other_action.set_version_number_using_target` instead
```

What I'm currently doing:
```ruby
increment_version_number_in_xcodeproj(version_number: "3.8.2", xcodeproj: "./path/Proj.xcodeproj", target: "MyApp")
```

Versions installed:
```
Using commander-fastlane 4.4.6
Using fastlane 2.134.0
Using fastlane-plugin-versioning 0.4.0
```

Any thoughts? Thanks.

**Comment by jdouglas-nz** [comment]
@caioremedio - yes ! oh man. There is a copy paste error in that action. 
apologies -- I'll whip up a fix for you shortly.

**Comment by caioremedio** [comment]
Ayt, thanks @jdouglas-nz :)

No hurry!

**Comment by jdouglas-nz** [comment]
@caioremedio please update and let me know how you go! 👌

**Comment by nick3389** [comment]
@jdouglas-nz Is there any update on that? The version is still 0.4.0

**Comment by jdouglas-nz** [comment]
@nick3389  - sorry! I released a new version yesterday.

**Comment by nick3389** [comment]
@jdouglas-nz Just updated and it works ok! thanx!

**Comment by caioremedio** [comment]
@jdouglas-nz Sorry for taking too long, I was out of town this week. 

Just updated and it worked like a charm. Thanks for fixing!
