### ISSUE TITLE
Error with increment_version_number_in_xcodeproj when setting scheme

### ISSUE THREAD

**Issue by 942v** [SiarheiFedartsou/fastlane-plugin-versioning#47]
Hi, 

When I execute:

`increment_version_number_in_xcodeproj(
        bump_type: bumpType,
        scheme: scheme
      ) `

It's changing all the configurations to the new value calculated from the correct scheme.

So basically I have 4 schemes:

Marketing versions:
A: 1.1.1
B: 2.2.2
C: 3.3.3
D: 4.4.4

When I do 
`increment_version_number_in_xcodeproj(
        bump_type: patch,
        scheme: D
      ) `

It executes: 
`xcodebuild -showBuildSettings -scheme D -project MyProject.xcodeproj`

And then the configurations get updated to:

A: 4.4.5
B: 4.4.5
C: 4.4.5
D: 4.4.5

If I add build_configuration_name 

The command fails with: 

` Unknown method 'set_version_number_using_scheme'`

**Comment by prathmeshranaut** [comment]
This function isn't coded in https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/master/lib/fastlane/plugin/versioning/actions/increment_version_number_in_xcodeproj.rb

The above PR fixes your issue.

**Comment by 942v** [comment]
nice thx!

**Comment by jdouglas-nz** [comment]
@942v  - I have finally merged this. apologies for the lag time. Please update and give it a go.
