### ISSUE TITLE
Can't get correct scheme

### ISSUE THREAD

**Issue by yonaskolb** [SiarheiFedartsou/fastlane-plugin-versioning#5]
I get an error saying `Couldn't find specified scheme'. I believe this is an issue when your specified scheme and target have different names.
The get_info_plist_path seems to want a scheme but the option for it is named target, as you can see on this line
https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/master/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb#L16
The target parameter should be renamed to scheme

**Comment by yonaskolb** [comment]
This used to work correctly in 0.2.5

**Comment by SiarheiFedartsou** [comment]
Hm, yes, I will consider renaming "target" to "scheme" or just adding alias(because this are synonyms in this case).
Also since 0.2.6 to work correctly your scheme(target) must be "shared"(sorry, for this restriction, it was done to fix #4). To make your scheme(target) shared go to "Manage schemes" in Xcode and tick "Shared" checkbox near your target name.

If it will not help, please, let me know and be free to reopen this issue.

**Comment by yonaskolb** [comment]
Passing in a scheme to the target parameter would have worked, but I have instead reverted to 0.2.5 as this is a breaking change, and I'd rather not have to pass in a scheme. 
In my opinion, it should work passing in a scheme OR a target plus a build_configuration_name if the value is configuration dependant

**Comment by dyang** [comment]
Same issue here. I'm bypassing this issue by passing in scheme as target. Hope to see a fix. :)

**Comment by ilyawiz** [comment]
yea - same here. passing scheme name for target name, otherwise the script asks me to select a scheme every time

**Comment by drosenstark** [comment]
@SiarheiFedartsou I'm not following. Is there a bug where you confuse target and scheme or not? Mine are always named the same so I wouldn't notice. Thanks for this plugin!

**Comment by yonaskolb** [comment]
Any updates on this?

**Comment by SiarheiFedartsou** [comment]
Hi all! Finally found a couple of hours to fix this issue :) Just released version 0.2.7. 
In 0.2.7 you can pass either `target` or `scheme` to actions. If you pass `target` it will work like 0.2.5, if you pass `scheme` it will work like 0.2.6.
Feel free to re-open this issue in case of similar problems.
