### ISSUE TITLE
Bug after call versioning 

### ISSUE THREAD

**Issue by devzhr** [SiarheiFedartsou/fastlane-plugin-versioning#57]
Hi,

in my info.plist file after the change of version, I have the `l'option` of text because in French but saved with the `l&#39;option`

cordially

**Comment by jdouglas-nz** [comment]
Hey, I might be inadvertently fixing this as a result of another issue (#59) I'm working on - basically a downstream dependency seems to serialise `.xcodeproj`'s differently to Xcode. I'll ask you to try again once the work has been done

**Comment by jdouglas-nz** [comment]
@devzhr  - I'm wondering if this issue is still at large now? I just pushed essentially a dependency bump which has an updated version of the xcodeproj gem. Hopefully this addresses your issue? 🤞

**Comment by jdouglas-nz** [comment]
I'm gonna close this as no longer an issue. feel free to re-open if this is not the case
