### ISSUE TITLE
Get list of builds in testflight and app store

### ISSUE THREAD

**Issue by lekeCoder** [SiarheiFedartsou/fastlane-plugin-versioning#58]
I am trying to fetch the list of builds `version` and `build_number` using Fastlane pilot builds but I keep getting this error: `[pilot] Fix TypeError in `list` by ignoring nil counts`. 
I want something like this:
+-----------+---------+----------+
|      Great App Builds          |
+-----------+---------+----------+
| Version # | Build # | Installs |
+-----------+---------+----------+
| 0.9.13    | 1       | 0        |
| 0.9.13    | 2       | 0        |
| 0.9.20    | 3       | 0        |
| 0.9.20    | 4       | 3        |
+-----------+---------+----------+

**Comment by jdouglas-nz** [comment]
Hey @lekeCoder, thanks for reaching out!

I'm not sure exactly what you're trying to achieve, but something definitely shouldn't be spitting out that message. 

The one thing that stands out to me is the `[pilot]` word in the print. 

Pilot is a [fastlane action](https://docs.fastlane.tools/actions/pilot/) for uploading builds to testflight. From what I can tell of the closest [plug-in action](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/master/lib/fastlane/plugin/versioning/actions/get_app_store_version_number.rb) provided by this plugin, we don't directly depend on Pilot or any of the fastlane actions to surface our results. I did find that it seems you [aren't alone](https://github.com/fastlane/fastlane/pull/17569) in your issue.

Can you please share a snippet of your Fastfile so I can have a little more context of what you're trying to achieve ?

**Comment by lekeCoder** [comment]
@jdouglas-nz thank you and sorry for the late reply. I found the right solution which is ```fastlane pilot builds```. This will list the builds in a tabular form.
