### ISSUE TITLE
Anything similar for Android?

### ISSUE THREAD

**Issue by codyrotwein** [SiarheiFedartsou/fastlane-plugin-versioning#7]
I need to increase the versionCode and versionName for all of my productFlavors in my gradle file. Would nice to have a plugin like this.

**Comment by SiarheiFedartsou** [comment]
@codyrotwein sorry, no, it is plugin for [fastlane](https://github.com/fastlane/fastlane), not for gradle. And for now we support iOS only. But feel free to add Android support by yourself and make a pull request.
